# A task ticket exists to make this configuration system better.
parameters:
  # Change this in root .env:
  ids.design_system: '%env(DESIGN_SYSTEM)%'
  # Defines all design systems. Only those in above two parameters are added to discovery.
  ids.design_systems:
    # Keyed by potential values of `ids.design_system`.
    # Values are arrays of class-string references of the Pinto Lists in the DS.
    mixtape:
      ds: !php/const PreviousNext\Ds\Mixtape\List\MixtapeLists::Lists
      additional:
        - !php/const PreviousNext\Ds\Common\List\CommonLists::Lists
    nswds:
      ds: !php/const PreviousNext\Ds\Nsw\Lists\NswLists::Lists
      additional:
        - !php/const PreviousNext\Ds\Common\List\CommonLists::Lists

  ids.project_dir: '%env(PROJECT_DIR)%'
  ids.webdriver.url: '%env(WEBDRIVER_URL)%'
  # Set TWIG_CACHE_DIRECTORY to empty string to use \sys_get_temp_dir().
  ids.twig.cache_dir: '%env(default::TWIG_CACHE_DIRECTORY)%'
  ids.ide: 'phpstorm'

  ids.build_objects:
    # File path relative to the Pinto Object class itself.
    directory: '/Tests/fixtures/snapshots'

  # Default values.
  env(WEBDRIVER_URL): 'http://firefox:4444/wd/hub'
  env(TWIG_CACHE_DIRECTORY): '/data/app/cache/twig'

# @todo other env vars and params, needed for command to work on host.
#base url: http://http/ #(host varyable)
#dump location for html: output/html/
#dump location for screenshots: output/screenshots/
